openapi: 3.0.3
info:
  title: MoEngage Inform API
  version: '1.0'
  description: |-
    API for MoEngage Inform, a unified messaging infrastructure for building and managing transactional alerts across multiple channels like SMS, Email, and Push.
tags:
  - name: Transactional Alerts
    description: Send transactional alerts using pre-configured templates.
servers:
  - url: 'https://api-{dc}.moengage.com/v1.0'
    description: Live Alerts Endpoint
    variables:
      dc:
        default: '01'
        description: 'The 'dc' in the API Endpoint URL refers to the MoEngage Data Center (DC). MoEngage hosts each customer in a different DC. You can find your DC number and replace the value of 'dc' in the URL by referring to the DC and API endpoint mapping [here](/api/introduction#data-centers). Your MoEngage Data Center (DC) can be 01, 02, 03, 04, 05, 06, or 101.'
  - url: 'https://sandbox-api-{dc}.moengage.com/v1.0'
    description: Test/Sandbox Alerts Endpoint
    variables:
      dc:
        default: '01'
        description: 'The 'dc' in the API Endpoint URL refers to the MoEngage Data Center (DC). MoEngage hosts each customer in a different DC. You can find your DC number and replace the value of 'dc' in the URL by referring to the DC and API endpoint mapping [here](/api/introduction#data-centers). Your MoEngage Data Center (DC) can be 01, 02, 03, 04, 05, 06, or 101. '
paths:
  /alerts/send:
    post:
      tags:
        - Transactional Alerts
      summary: Send Transactional Alert
      description: "This API is used to trigger a transactional message/alert to the user via one or more configured channels."
      x-mint:
        content: |
          #### Rate Limit
          The default rate limit is 10K RPM.
      security:
        - basicAuth: []
          moeAppKey: []
      requestBody:
        required: true
        description: The payload containing the alert identifier, transaction details, and recipient information for each channel.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InformRequest'
            examples:
              singleChannelWithoutPersonalization:
                summary: Single Channel (SMS) without Personalization
                value:
                  alert_id: "636b77e6e2cf83277195fb60"
                  alert_reference_name: "Demo_ID"
                  user_id: "USER_12345"
                  transaction_id: "TXN_ABCDEF123"
                  payloads:
                    SMS:
                      recipient: "1234567890"
              multichannelWithoutPersonalization:
                summary: Multichannel Without Personalization
                value:
                  alert_id: "636b77e6e2cf83277195fb60"
                  alert_reference_name: "Demo_ID"
                  user_id: "USER_ID"
                  transaction_id: "YOUR_TRANSACTION_ID_VA